# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# permalink:        /:title/

# Setup
title:            ISSA
tagline:          'ISSA'
description:      'The 2016 International Symposium on  IoT  Systems, Services and Analytics for Developing Worlds (ISSA2016).'
url:              http://issadw.github.io
baseurl:          /

author:
  name:           'Kien Nguyen'
  url:            https://twitter.com/ntk148v

paginate:         10

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/issadw/issadw.github.io
